
##日期设置,注意日期需要引号，不然会解析成timestamp
date:
  start: "2011-01-01 00:00:00"
  end: "2011-12-31 23:59:59"

##返回信息
result:
  SUCCESS: {code:0, message:操作成功}
  ERROR_FAIL: {code:10001, message:操作失败}
  ERROR_VERIFY: {code:10003, message:请输入正确的验证码}
  ERROR_SYSTEM_BUSY: {code: 10100, message:系统繁忙}
  ERROR_SYSTEM_TIMEOUT: {code: 10101, message: 活动已结束}
  ERROR_SYSTEM_ISNOT_LOGIN: {code:10102, message: 请登录您的QQ账号}


### --= 服务器配置信息  - 非特殊情况 - 请勿修改 =--

# php端和”上传web服务器CGI”约定的私钥
private_key : tae_uploadpic_1

# 上传文件服务器配置
file_server:
  upload_url: http://upload.act.qq.com/cgi-bin/up_pic